### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by Sitebase** [bubobox/bem-js#1]
See for more info this issue comment: https://github.com/bubobox/components/issues/93#issuecomment-122920572

**Comment by mahammedzkhan** [comment]
Any suggestions which library I should use for the immutability?

**Comment by Sitebase** [comment]
This is the one everyone in the react community is using:
https://facebook.github.io/immutable-js/

**Comment by mahammedzkhan** [comment]
I've tried using the fromJS function stated here in the documentation: 
http://facebook.github.io/immutable-js/docs/#/fromJS

But it doesn't make the 'block' object immutable. Unit test still fails.

**Comment by JorgenEvens** [comment]
Isn't using a library for a utility as simple as this a bit overkill?

By modifying the constructor of block you would be able to build in the immutability yourself.

```
function Block(blockName, modifiers, befores, afters) {
    this.modifiers = modifiers || [];
    this.befores = befores || [];
    this.afters = afters || [];
    this.name = blockName;
}

Block.prototype.mod = function () {
        var mod = this.modifiers.slice();
        var befores = this.befores.slice();
        var afters= this.afters.slice();

        for (var _i = 0; _i < arguments.length; _i++) {
            mod.push(arguments[_i]);
        }

        return new Block(this.name, mod, befores, afters);
    };
}
```

What are your thoughts on this @Sitebase ?

**Comment by Sitebase** [comment]
@JorgenEvens agreed

**Comment by mahammedzkhan** [comment]
Unit test passed, immutability is implemented.
